version: '3.1'
services:
  elasticsearch:
    container_name: els
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elasticnetwork
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.10.4
    ports:
      - 5601:5601
    depends_on: 
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL = http://localhost:9200
    networks: 
      - elasticnetwork
networks:
  elasticnetwork:
    driver: bridge
volumes: 
  elasticsearch-data: